### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by myungwoo** [myungwoo/react-domjudge#1]
그냥 생각난 것들
- [x] Contest state, Timer를 로컬 시간이 아닌 서버 시간과 동기화 하기 / 0e856ca2dd84bc8544565ab745e7cf366164d5a2
- [x] Loading 이미지 react로 바꾸기 / 99e008810730efcb8cbe02472e6a2c76fa542d3a
- [x] App이 mount 될 때 가지고 있는 jwt-token이 유효한지 검사하기 & 유저 정보 갱신 / ca3ffbfc496727ced70a4dd7abe14681dffefae8
- [x] User Info dialog를 responsive 하게 만들기 / 57d220e49e37a772382a953ac91d816cc030cb5f
- [x] App에서 Loading, Error 메시지를 모바일에서 작게 보이게 하기 / 1ce761afa9cef391fb4d039f04e96116ce5509b4
- [x] Console에 프로젝트명 띄우기 / 9fb4114c365627b1fce34c0e704960d3e45a87d3
- [x] 제출 상세보기에서 제출물을 볼 수 있으면 좋을 듯 (자리 이동 등의 상황에서)

API request catch 시에 하는 일들
- [x] Something went wrong, please reload the app.

App loading 시 할 일들
- [x] jwt-token의 유효성 검사
- [x] localStorage의 userdata 갱신
- [x] api 서버 유효성 검사 (api 응답 여부 / DB 연결 여부 / domjudge api 연결 여부)

Contest 관련 기능 구현
- [x] Api에서 contest 관련 구현하기
- [x] Contest 관련 정보 client에 가지고 있기
- [x] Active contest가 하나도 없는 경우 로그인 화면에서 No active contest 알려주기
- [x] App이 mount 될 때 active contest 정보 새로 고침하기
- [x] Timer 구현
- [x] Contest switching 구현하기
- [x] Overview 페이지에서 contest state에 따른 정보 표시 구현 / cfe5be7bf7b1ecb092b8739f6180badf50a22fbb

생각할 것들
- [x] No active contest 메시지를 api에서 검사할 필요가 있을까? Contest.getList에서 확인하는 것은 어떨까?
- [x] node.js의 MySQL max db connections 어느정도 되는지 확인하기
- [ ] api 에서 body를 validate 해주는 좋은 패키지가 없나
- [ ] 한 팀에 여러 user가 붙을 경우 refresh 로직에 대해 생각해줄 필요가 있다.
- [ ] Enabled contest 만 가져오기. 다른 것들도 마찬가지.
- [x] await db 시에 동시에 할 수 있는 것들 알아보기.
- [ ] React shouldComponentUpdate를 통한 최적화

Submission 관련
- [x] Submissions 목록 보이기 / 9703096844d32608790f190479c004903f6b0e15
- [x] Submit solution 구현하기 (api / react) / 765d08dcfd5eec28d05cd91bc7105610d4942aba
- [x] Submission detail 페이지 / 6d2b856d882a8af405e8139ae36ec6df39d65c61
- [x] Submission detail을 읽었을 때, judging.seen = 1로 바꾸기

Auditlog
- [x] User login / bd0f48ad0e335c3cf640d302730c8e2485e26c37
- [x] User logout / bd0f48ad0e335c3cf640d302730c8e2485e26c37
- [x] Submission add / bd0f48ad0e335c3cf640d302730c8e2485e26c37
- [x] Clarification add

Confirm
- [x] On submit files / d13a9fb5c46fe3010be7eb329b55c4eca8b0f55f
- [x] On send clarification request / c6c92626b467ad190179ee0a3512489c3b74550e
